import { IconLink } from "@/components/links/iconLink";

export const aws_services_logos = [
  <IconLink
    key="api-gateway"
    src="/api-gateway.svg"
    href="https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html"
    alt="Api Gateway"
  />,

  <IconLink
    key="cloudformation"
    src="/cloudformation.svg"
    href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html"
    alt="Cloud Formation"
  />,
  <IconLink
    key="cloudfront"
    src="/cloudfront.svg"
    alt="CloudFront"
    href="https://aws.amazon.com/cloudfront/"
  />,
  <IconLink
    key="cloudwatch"
    src="/cloudwatch.svg"
    alt="CloudWatch"
    href="https://aws.amazon.com/cloudwatch/"
  />,
  <IconLink
    key="codedeploy"
    src="/codedeploy.svg"
    alt="CodeDeploy"
    href="https://aws.amazon.com/codedeploy/"
  />,
  <IconLink
    key="cognito"
    src="/cognito.svg"
    alt="Cognito"
    href="https://aws.amazon.com/cognito/"
  />,
  <IconLink
    key="dynamodb"
    src="/dynamodb.svg"
    alt="DynamoDB"
    href="https://aws.amazon.com/dynamodb/"
  />,
  <IconLink
    key="ec2"
    src="/ec2.svg"
    alt="EC2"
    href="https://aws.amazon.com/ec2/"
  />,
  <IconLink
    key="iam"
    src="/iam.svg"
    alt="IAM"
    href="https://aws.amazon.com/iam/"
  />,
  <IconLink
    key="kinesis"
    src="/kinesis.svg"
    alt="Kinesis"
    href="https://aws.amazon.com/kinesis/"
  />,
  <IconLink
    key="lambda"
    src="/lambda.svg"
    alt="Lambda"
    href="https://aws.amazon.com/lambda/"
  />,
  <IconLink
    key="rds"
    src="/rds.svg"
    alt="RDS"
    href="https://aws.amazon.com/rds/"
  />,
  <IconLink
    key="route53"
    src="/route53.svg"
    alt="Route 53"
    href="https://aws.amazon.com/route53/"
  />,
  <IconLink
    key="s3"
    src="/s3.svg"
    alt="S3"
    href="https://aws.amazon.com/s3/"
  />,
  <IconLink
    key="sns"
    src="/sns.svg"
    alt="SNS"
    href="https://aws.amazon.com/sns/"
  />,
  <IconLink
    key="sqs"
    src="/sqs.svg"
    alt="SQS"
    href="https://aws.amazon.com/sqs/"
  />,
  <IconLink
    key="vpc"
    src="/vpc.svg"
    alt="VPC"
    href="https://aws.amazon.com/vpc/"
  />,
];

export const techlist = [
  <IconLink src="/aws.svg" alt="AWS" key="aws" href="https://aws.amazon.com" />,
  <IconLink
    src="/docker.svg"
    alt="Docker"
    key="docker"
    href="https://docs.docker.com/"
    width={115}
    height={115}
  />,
  <IconLink
    src="/git.svg"
    alt="JS"
    key="git"
    href="https://git-scm.com/doc"
    width={73}
    height={73}
  />,
  <IconLink
    src="/github-icon.svg"
    alt="GITHUB"
    key="github"
    href="https://github.com/"
    width={30}
    height={30}
  />,
  <IconLink
    src="/kafka.svg"
    alt="KAFKA"
    key="kafka"
    href="https://kafka.apache.org/"
    width={19}
    height={19}
  />,
  <IconLink
    src="/elasticsearch.svg"
    alt="ELASTICSEARCH"
    key="elasticsearch"
    href="https://www.elastic.co/guide/index.html"
  />,
  <IconLink
    src="/terraform.svg"
    alt="TERRAFORM"
    key="terraform"
    href="https://www.terraform.io/"
    width={45}
    height={45}
  />,
  <IconLink
    src="/vercel.svg"
    alt="VERCEL"
    key="vercel"
    href="https://vercel.com"
  />,
  <IconLink
    src="/sql-server.svg"
    alt="SQL"
    key="sql"
    href="https://www.microsoft.com/pt-br/sql-server/sql-server-downloads"
    width={80}
    height={80}
  />,
  <IconLink
    src="/firebase.svg"
    alt="FIREBASE"
    key="firebase"
    href="https://firebase.google.com"
    width={37}
    height={37}
  />,
  <IconLink
    src="/nodejs.svg"
    alt="NODEJS"
    key="nodejs"
    href="https://nodejs.org/docs/latest/api/"
    width={75}
    height={75}
  />,
  <IconLink
    src="/fastapi.svg"
    alt="FASTAPI"
    key="fastapi"
    href="https://fastapi.tiangolo.com/"
    width={45}
    height={45}
  />,
  <IconLink
    src="/nextjs.svg"
    alt="NEXTJS"
    key="nextjs"
    href="https://nextjs.org/"
    width={75}
    height={75}
  />,
  <IconLink
    src="/react.svg"
    alt="REACTJS"
    key="react"
    href="https://react.dev/"
    width={40}
    height={40}
  />,
];

export const languages_list = [
  <IconLink
    src="/javascript.svg"
    alt="JS"
    href="https://www.w3schools.com/js/"
    key="js"
  />,
  <IconLink
    src="/typescript.svg"
    alt="TS"
    href="https://www.typescriptlang.org/"
    key="ts"
  />,
  <IconLink
    src="/python.svg"
    alt="PY"
    href="https://www.python.org/doc/"
    key="py"
    width={120}
    height={120}
  />,
  <IconLink
    src="/golang.svg"
    alt="GO"
    href="https://go.dev/doc/"
    key="go"
    width={80}
    height={80}
  />,
];

export const frameworks_list = [
  <IconLink
    src="/amplify.svg"
    alt="Amplify"
    key="amplify"
    href="https://aws.amazon.com/amplify"
  />,
  <IconLink
    src="/cdk.svg"
    alt="CDK"
    key="cdk"
    href="https://aws.amazon.com/cdk"
  />,
  <IconLink
    src="/codebuild.svg"
    alt="CodeBuild"
    key="codebuild"
    href="https://aws.amazon.com/codebuild"
  />,
  <IconLink
    src="/codepipeline.svg"
    alt="CodePipeline"
    key="codepileline"
    href="https://aws.amazon.com/codepipeline"
  />,
  <IconLink
    src="/costexplorer.svg"
    alt="CostExplorer"
    key="costexplorer"
    href="https://aws.amazon.com/aws-cost-management/aws-cost-explorer/"
  />,
  <IconLink
    src="/elasticache.svg"
    alt="Elasticache"
    key="elasticache"
    href="https://aws.amazon.com/elasticache"
  />,
  <IconLink
    src="/ecs.svg"
    alt="ECS"
    key="ecs"
    href="https://aws.amazon.com/ecs"
  />,
  <IconLink
    src="/eventbridge.svg"
    alt="Event Bridge"
    key="eventbridge"
    href="https://aws.amazon.com/eventbridge"
  />,
  <IconLink
    src="/kms.svg"
    alt="KMS"
    key="kms"
    href="https://aws.amazon.com/kms"
  />,
  <IconLink
    src="/opensearch.svg"
    alt="OpenSearch"
    key="opensearch"
    href="https://aws.amazon.com/opensearch-service/"
  />,
  <IconLink
    src="/secretsmanager.svg"
    alt="Secrets Manager"
    key="secretsmanager"
    href="https://aws.amazon.com/secrets-manager/"
  />,
  <IconLink
    src="/stepfunctions.svg"
    alt="Step Functions"
    key="stepfunctions"
    href="https://aws.amazon.com/step-functions"
  />,
  <IconLink
    src="/systemsmanager.svg"
    alt="Systems Manager"
    key="systemsmanager"
    href="https://aws.amazon.com/systems-manager"
  />,
  <IconLink
    src="/trustedadvisor.svg"
    alt="Trusted Advisor"
    key="trustedadvisor"
    href="https://aws.amazon.com/premiumsupport/technology/trusted-advisor/"
  />,
  <IconLink
    src="/wellarchitectedtool.svg"
    alt="Well Architected Tool"
    key="wellarchitectedtool"
    href="https://aws.amazon.com/well-architected-tool"
  />,
];
